set guifont=SF_Mono
set autoindent
set expandtab
set shiftround
set shiftwidth=4
set smarttab
set tabstop=4

set hlsearch
set ignorecase
set incsearch
set smartcase

set lazyredraw

set display+=lastline
set encoding=utf-8
set linebreak
set scrolloff=1
set sidescrolloff=5
syntax enable
set wrap
set textwidth=60

set laststatus=2
set ruler
set wildmenu
set cursorline
set number
"set relativenumber
set visualbell
set title

filetype plugin on
