set guifont=Jetbrains_Mono:h13
set autoindent
set expandtab
set shiftround
set shiftwidth=4
set smarttab
set tabstop=4
set lcs+=space:·

set hlsearch
set ignorecase
set incsearch
set smartcase

set lazyredraw

set display+=lastline
set encoding=utf-8
set linebreak
set scrolloff=1
set sidescrolloff=5
syntax enable
set wrap
set textwidth=72
set colorcolumn=72
set laststatus=2
set ruler
set wildmenu
set cursorline
set number
"set relativenumber
set visualbell
set title

set completeopt=menuone,longest

set nocompatible
filetype plugin on

let g:ycm_min_num_of_chars_for_completion=2
let g:ycm_min_num_identifier_candidate_chars=2

packloadall

map <F8> : !clang -g % && ./a.out <CR>

if has('python')
  map <C-K> :pyf /opt/homebrew/Cellar/clang-format/19.1.5/share/clang/clang-format.py<cr>
  imap <C-K> <c-o>:pyf /opt/homebrew/Cellar/clang-format/19.1.5/share/clang/clang-format.py<cr>
elseif has('python3')
  map <C-K> :py3f /opt/homebrew/Cellar/clang-format/19.1.5/share/clang/clang-format.py<cr>
  imap <C-K> <c-o>:py3f /opt/homebrew/Cellar/clang-format/19.1.5/share/clang/clang-format.py<cr>
endif
