;;; org-books-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-books.el

(autoload 'org-books-cliplink "org-books" "\
Clip link from clipboard." t)
(autoload 'org-books-add-url "org-books" "\
Add book from web URL.

(fn URL)" t)
(autoload 'org-books-add-isbn "org-books" "\
Add book from ISBN.

(fn ISBN)" t)
(autoload 'org-books-add-book "org-books" "\
Add a book (specified by TITLE and AUTHOR) to the `org-books-file'.

Optionally apply PROPS.

(fn TITLE AUTHOR &optional PROPS)" t)
(autoload 'org-books-rate-book "org-books" "\
Apply RATING to book at current point.

(fn RATING)" t)
(register-definition-prefixes "org-books" '("org-books-"))

;;; End of scraped data

(provide 'org-books-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-books-autoloads.el ends here
