;;; org-drill-table-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from org-drill-table.el

(autoload 'org-drill-table-generate "org-drill-table" "\
Use a table at the current heading to generate org-drill cards.

HEADING is the title to use for each card.

TYPE is a string, of one of the card types in `org-drill-card-type-alist'.

INSTRUCTIONS is a string describing how to use the card.

(fn HEADING TYPE INSTRUCTIONS)" t)
(autoload 'org-drill-table-update "org-drill-table" "\
Update an existing org drill table.
Suitable for adding to `org-ctrl-c-ctrl-c-hook'." t)
(autoload 'org-drill-table-update-all "org-drill-table" "\
Call `org-drill-table-update' on each table in the buffer." t)
(register-definition-prefixes "org-drill-table" '("org-drill-"))

;;; End of scraped data

(provide 'org-drill-table-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-drill-table-autoloads.el ends here
