;;; lem-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from lem.el

(autoload 'lem "lem" "\
Open lem, a Lemmy client.
Load current user's instance posts." t)
(autoload 'lem-auth-fetch-token "lem" "\
Return jwt token for USERNAME.

(fn &optional USERNAME)")
(register-definition-prefixes "lem" '("lem-"))


;;; Generated autoloads from lem-api.el

(defvar lem-auth-token nil "\
A user auth token for a lemmy instance.
Logging in will set this. You can also save it in your init.el.")
(register-definition-prefixes "lem-api" '("lem-"))


;;; Generated autoloads from lem-post.el

(register-definition-prefixes "lem-post" '("lem-"))


;;; Generated autoloads from lem-request.el

(register-definition-prefixes "lem-request" '("lem-def-request"))


;;; Generated autoloads from lem-search.el

(register-definition-prefixes "lem-search" '("lem-"))


;;; Generated autoloads from lem-ui.el

(register-definition-prefixes "lem-ui" '("lem-" "vtable-"))

;;; End of scraped data

(provide 'lem-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; lem-autoloads.el ends here
